import { StyleSheet} from 'react-native';
import { isDark } from "../theme/themeContext";
import { colors } from "../utils/colors";
import { DevHeight, DevWidth } from "../utils/device";


export const styledComponentsSheet = StyleSheet.create({
  logoContainer: {
    alignItems: 'center',
    marginTop: 50,
  },
  buttonContainer: {
    flexDirection: 'row',
    zIndex: 1,
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  buttonContainer1: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  loginLogoBigCircle: {
    height: 110,
    width: 110,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
  },
  loginLogoCircle: {
    height: 80,
    width: 80,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialLogoCircle: {
    height: 60,
    width: 60,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputData: {
    fontSize: 14,
    padding: 10,
  },
  iconInputContainer: {
    borderBottomWidth: 1,
    flexDirection: 'row',
    marginVertical: 10,
  },
  inputContainer1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
  },
  checkBoxContainer: {
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
  },
  checkBoxContainer1: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: 10,
  },
  inputContainerCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
  },
  checkBox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: colors.greyVar4,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomStyle: {
    borderBottomWidth: 1,
    width: '30%',
  },
  socialLogoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    margin: 30,
  },
  textContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'flex-end',
    marginBottom: 30,
    paddingTop: 100,
  },
  textContainer1: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'flex-end',
  },
  otpInput: {
    borderWidth: 1,
    fontSize: 20,
    textAlign: 'center',
    width: 45,
    height: 45,
    borderRadius: 7,
    justifyContent: 'space-around',
    color: colors.black,
  },
  splashScreenContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainerSecond: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  halfCircleSecond: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
    width: '20%',
    height: 40,
    alignSelf: 'center',
    zIndex: -1,
    top: 15,
  },
  modalContentSecond: {
    backgroundColor: colors.white,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 10,
  },
  halfCircle: {
    backgroundColor: isDark() ? colors.darkModeVar4 : colors.white,
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
    width: '30%',
    height: 60,
    alignSelf: 'center',
    top: 15,
    overflow: 'hidden',
  },
  halfCircle2: {
    backgroundColor: isDark() ? colors.darkModeVar4 : colors.white,
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
    width: '18%',
    height: 48,
    alignSelf: 'center',
    top: 15,
    overflow: 'hidden',
  },
  modalContent: {
    backgroundColor: isDark() ? colors.darkModeVar4 : colors.white,
    padding: 20,
    borderRadius: 15,
    width: '80%',
    maxWidth: 400,
  },
  modalContent1: {
    backgroundColor: isDark() ? colors.darkModeVar4 : colors.white,
    borderRadius: 15,
    width: DevWidth / 1.3,
    maxWidth: 400,
  },
  textWithG: {
    backgroundColor: colors.primaryVar4,
    textAlign: 'center',
    borderRadius: 5,
    height: 25,
    color: colors.primaryVar3,
  },
  qrImgView: {
    backgroundColor: colors.white,
    padding: 10,
    elevation: 4,
    marginTop: 35,
    borderRadius: 10,
    shadowColor: colors.greyVar3,
    alignSelf: 'center',
  },
  btnContainer: {
    marginTop: 330,
    bottom: 35,
    marginHorizontal: 20,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  modalBg: {
    borderRadius: 15,
    backgroundColor: isDark() ? colors.darkModeVar6 : colors.primaryVar1,
  },
  card1: {
    padding: 10,
    elevation: 2,
    marginHorizontal: 20,
    marginTop: 18,
    flexDirection: 'row',
    borderRadius: 6,
    backgroundColor: isDark() ? colors.darkModeVar7 : colors.primaryVar1,
  },
  topCard: {
    padding: 10,
    margin: 20,
  },
  circleBg: {
    position: 'absolute',
    top: 25,
    left: 27,
    height: 13,
    width: 13,
    borderRadius: 13,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleBg1: {
    height: 10,
    width: 10,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: colors.green,
  },
  iconContainer2: {
    backgroundColor: colors.primaryVar3,
    height: 32,
    width: 32,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  whiteBgContact: {
    height: '100%',
    width: '100%',
    borderTopLeftRadius: 45,
    borderTopRightRadius: 45,
    overflow: 'hidden',
  },
  progressBarsContainer: {
    left: 8,
    marginTop: 10,
    position: 'absolute',
    flex: 1,
  },
  emojiText: {
    fontSize: 18,
    color: colors.yellow,
    margin: 5,
  },
  chatViewCommonHeader: {
    height: DevWidth / 4.2,
    borderBottomRightRadius: 25,
    borderBottomLeftRadius: 25,
    elevation: 1,
  },
  footerFirstView: {
    alignItems: 'center',
    height: DevHeight / 9.5,
    paddingHorizontal: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flexDirection: 'row',
    justifyContent: 'center',
  },
});
