export const TOKEN_KEY = 'access_token';
export const REFRESH_TOKEN_KEY = 'refreshtoken';
export const BASE_URL = 'http://13.235.83.139:3001/api/';
// export const BASE_URL = 'http://localhost:4000/api/';
export const IMAGE_URL = 'https://d3f1l8wc4pf29x.cloudfront.net/';
export const SOCKET_PATH = '/socket.io';
// export const SOCKET_SERVER = 'http://192.168.1.3:4000/api';
// export const SOCKET_SERVER = 'http://localhost:4000/api/';
export const SOCKET_SERVER = 'http://13.235.83.139:3001';
// export const PAYMENT_TESTING_KEY = "pk_test_51PWASOArAKnrVFwl5jXNCcCYXvWI2vKSZg24EzvlenTGYA02Z8aGMwLedspZkgTWjdNnGG3KRNJNxwpLqfFC0AwN00zzsz0sOF";
export const PAYMENT_TESTING_KEY = "pk_test_51OPWpdBUDAbweOxj6WA42K0JAP0mIqe6TupTYASGvN7BY18Wfx3GoKzEBzZPvFyOkJ5OXgvqNp1rmbRApVQRBLqb00spyokXIC";

export const URL = {
  LOGIN: 'auth/signin',
  SIGN_UP: 'auth/signup',
  SEND_OTP: 'auth/send-otp',
  VERIFY_OTP: 'auth/verify-otp',
  USERS: 'auth/users',
  GET_PROFILE: 'auth/get-user',
  CONVERSATIONS: 'chat/conversations',
  SEND_MESSAGE: 'chat/send-message',
  RESEND_OTP: 'auth/otp',
  GROUP_CREATE: 'group/create',
  USER_GROUPS: 'group/user-groups',
  SEND_GROUP_MESSAGE: 'group/send-message',
  GROUP_MESSAGES: 'group/messages',
  RESET_PASSWORD: 'auth/reset-password',
  FORGOT_PASSWORD: 'auth/forgot-password',
  LOG_OUT: 'auth/logout',
  REFRESH_TOKEN: 'auth/refreshtoken',
  PRODUCT_SUB: 'home/product-sub-categories',
  GET_VENDOR_LIST: 'home/vendors',
  GET_PRODUCT_LISTING: 'vendor/product',
  ADD_CART: 'home/add-to-cart',
  GET_CART: 'home/cart',
  DELETE_CART: 'home/cart?id=',
  REMOVE_PRODUCT_FROM_CART: 'home/remove-from-cart',
  ADD_FAVOURITE: 'user/favourite',
  USER_FAVOURITE: 'user/favourite',
  GET_PRODUCT_CATEGORY: 'home/product-categories',
  GET_PRODUCT_SUB_CATEGORY: 'home/product-sub-categories',
  GET_BRANDS_LIST: 'home/brands',
  GET_UNREAD_MESSAGE_LIST: 'user/chat-unread-count',
  VENDOR_VIEW_REVIEWS: 'vendor/reviews',
  PAYMENT_CARD: 'payment/card',
  CHECKOUT: 'home/checkout',
  MODELS: 'vendor/models',
  MAKE_ORDER: 'home/order',
  VERIFY_PAYMENT: 'payment/payment',
  USER_METRICS: 'user/metrics',
  VENDOR_METRICS: 'vendor/metrics',
  VENDOR_PDF_DOWNLOAD: 'vendor/download-pdf',
  USER_ORDER: 'user/order',
  USER_CANCEL_ORDER: 'user/cancel-order',
  USER_ACCEPT_ORDER: 'user/accept-order',
  USER_REMOVE_ORDER: 'user/remove-order-product',
  USER_ADD_AUTH_PERSON: 'user/add-authperson',
  USER_PICK_ORDER: 'user/pickup-order',
  RETURN_ORDER: 'user/return-order',
  HOME_SIGNED_URL: 'home/signed-url',
  UPLOAD_COI: 'user/upload-oder-coi',
  USER_RAISE_ISSUE: 'user/raise-issue',
  USER_REASONS: 'user/reason',
  USER_REVIEW: 'user/review',
  USER_VERIFICATION: 'user/verification',
  USER_UPDATE_USER: 'user/update-user',
  USER_SUBJECT_HELP: 'user/subject',
  USER_CONTACT: 'user/contactus',
  USER_SEND_MESSAGE: 'user/message',
  USER_CHATS: 'user/chats',
  USER_CREATE_CHAT: 'user/create-chat',
  UPLOAD_ORDER_COI: 'upload-oder-coi',
  VENDOR_BECOME_VENDOR: 'vendor/become-vendor',
  VENDOR_VENDOR_DETAIL: 'vendor/vendor-detail',
  DELETE_DISCOUNT: 'vendor/delete-discount',
  DELETE_CHARGES: 'vendor/delete-charges',
  VENDOR_UPDATE_VENDOR: 'vendor/update-vendor',
  USER_DELETE_PUBLIC_USER: 'user/delete-public-profile',
  ADD_UPDATE_VENDOR_DOCUMENTS: 'vendor/documents',
  CHANGE_CART_DATE: 'home/change-cart-date',
  CHANGE_ORDER_DATE: 'user/change-order-date',
  PICKED_UP: 'vendor/order-status',
  GET_SUBSCRIPTION_PLANS:
    'vendor/subscription-plan?type=VENDORSUBSCRIPTIONLIST',
  GET_NOTIFICATION_SETTINGS: 'user/get-notification-settings',
  SAVE_NOTIFICATION_SETTINGS: 'user/notification-settings',
  VENDOR_INVENTORY: 'vendor/inventory',
  VENDOR_KIT: 'vendor/includedkit',
  VENDOR_PRODUCT_LIST: 'vendor/product-list',
  VENDOR_FEE_CHARGE: 'vendor/fees-and-charges',
  VENDOR_GET_PROMOTION: 'vendor/promotion',
  PAYMENT_INTENT: 'payment/payment-intent',
  GET_NOTIFICATION: 'home/notifications',
  REMOVE_UNAVAILABLE_ITEMS: 'home/remove-unavailable-from-cart',
  ADD_DISCOUNT: 'vendor/add-discount',
  ADD_CHARGES: 'vendor/add-charge',
  VENDOR_PRODUCTS: 'vendor/vendor-product-list',
  VENDOR_ADD_ORDER: 'vendor/add-products-to-order',
  VENDOR_BLOCK_DATES: 'vendor/block-dates',
  USER_SUBMIT_ID: 'user/submitid',
  USER_VERIFY_ID: 'user/verifyid',
  UPDATE_UNNREAD_NOTIFICATION: 'user/update-unread-notification',
  MOVE_TO_TOP: 'vendor/move-to-top',
  ADD_ACH: 'payment/add-ach',
  LINK_ACCOUNT: 'payment/link-account',
  CONNECTED_ACCOUNT: 'payment/connected-account',
  CREATE_SUBSCRIPTION: 'vendor/create-subscription',
  PAYMENT_INTENT_ADD_CARD: 'payment/intent',
  PAYMENT_REFUND: 'payment/refund',
  USER_PRIVACY: 'user/privacy', //not working because of database changes 
  ADMIN_PRIVACY: 'admin/privacy',
  READ_NOTIFICATION: 'home/read-notification',
  DUPLICATE_PRODUCT: 'vendor/duplicate-product',
  SETUP_INSURANCE: 'vendor/insurance',
  DISPUTE: 'vendor/dispute',
  DISPUTE_IMAGE: 'vendor/dispute-image',
  DISPUTE_INTENT: 'payment/dispute-intent',
  DISPUTE_PAYMENT: 'vendor/dispute-payment',
  DEFAULT_CARD: 'payment/default-card',
  PRIVACY_CATEGORY: 'admin/privacy-category',
};
