export const HAS_ONBOARDED = 'has_onboarded';

export const GOOGLE_MAP_APIKEY = 'AIzaSyCWbsC3b6QgedZG8VQe2ux5lovNGxTptZM';

export const COLORS = {
  Yellow: '#F1C40F',
  titleOpacty: 'rgba(255, 255, 255, 0.6)',
  darkTitle: 'rgba(17, 17, 17, 1)',
  // primary: 'rgba(111, 180, 186, 1)',
  // primary: '#F0FFFF',
  primary: "#0098FF",
  // primary: "#3C0E66",
  switch: '#6FB4BA',
  disablePrimary: 'rgba(111, 180, 186, 0.6)',
  bg: 'rgba(17, 17, 17, 1)',
  black: 'rgba(0, 0, 0, 1)',
  heading: '#FFFFFF',
  subheading: '#DODODO',
  icon: '#777777',
  selected: 'rgba(119, 119, 119, 0.2)',
  white: 'rgba(255, 255, 255, 1)',
  inputBg: 'rgba(51, 51, 51, 1)',
  cardBg: 'rgba(28, 28, 28, 1)',
  iconDark: 'rgba(30, 30, 30, 1)',
  red: 'rgba(192, 57, 43, 1)',
  crossRed: '#CC0000',
  blurBlack: 'rgba(0, 0, 0, 0.8)',
  minBlurBlack: 'rgba(30, 30, 30, 0.7)',
  iconGrey: 'rgba(163, 169, 182, 1)',
  fullRed: 'rgba(204, 0, 0, 1)',
  calendarPickup: 'rgba(111, 180, 186, 1)',
  calendarPaid: 'rgba(165, 170, 170, 1)',
  transparent: 'transparent',
  multiWeekDiscount: 'rgba(111, 185, 153, 1)',
  calendarDiscount: 'rgba(111, 143, 186, 1)',
  weekendDiscount: 'rgba(154, 111, 186, 1)',
  orange: 'rgba(248, 102, 36, 1)',
  blurBlue: 'rgba(0, 133, 255, 0.15)',
  blurYellowBg: '#ffeb4d33',
  blurYellow: 'rgba(204, 122, 0, 0.17)',
  mustard: 'rgba(204, 122, 0, 1)',
  darkGreen: '#519197',
};

export const SCREENS = {
  app: 'App',
  login: 'Login',
  signup: 'SignUp',
  forgotPassword: 'ForgotPassword',
  VerifyOTP: 'VerifyOTP',
  ResetPassword: 'ResetPassword',
  verifyId: 'VerifyId',
  MessageOrders: 'MessageOrders',
  home: 'Home',
  HomeStackNavigator: 'HomeStackNavigator',
  ChatStackNavigator: 'ChatStackNavigator',
  StatusStackNavigator: 'StatusStackNavigator',
  SearchStackNavigator: 'SearchStackNavigator',
  CallStackNavigator: 'CallStackNavigator',
  MessageStackNavigator: 'MessageStackNavigator',
  SettingsStackNavigator: 'SettingsStackNavigator',
  search: 'Search',
  Chat: 'Chat',
  Status: 'Status',
  CallDetail: 'CallDetail',
  Call: 'Call',
  cart: 'Cart',
  ContactInfo: 'ContactInfo',
  message: 'Messages',
  dashboard: 'Dashboard',
  trustedvendors: 'TrustedVendors',
  vendorfilter: 'VendorFilter',
  notification: 'Notification',
  rentItem: 'rentItem',
  productDetail: 'productDetail',
  vendorStore: 'vendorStore',
  SearchFilter: 'SearchFilter',
  ProductPage: 'ProductPage',
  CreateDispute: 'CreateDispute',
  VendorStoreReviews: 'VendorStoreReviews',
  CartCheckOut: 'CartCheckOut',
  InsuranceDetail: 'InsuranceDetail',
  ChatRoom: 'ChatRoom',
  Metrics: 'Metrics',
  Orders: 'Orders',
  BecomeVendor: 'BecomeVendor',
  Insurance: 'Insurance',
  SetupInsurannce: 'SetupInsurannce',
  PaymentMethod: 'PaymentMethod',
  SubscriptionPayment: 'SubscriptionPayment',
  NoInternetScreen: 'NoInternetScreen',
  NotificationSetting: 'NotificationSetting',
  Verification: 'Verification',
  RenterProfile: 'RenterProfile',
  Favourite: 'Favourite',
  HelpCenter: 'HelpCenter',
  TermsCondition: 'TermsCondition',
  PrivacyPolicy: 'PrivacyPolicy',
  CommunityGuidelines: 'CommunityGuidelines',
  OrderRequested: 'OrderRequested',
  AuthrisationPerson: 'AuthrisationPerson',
  LeaveReview: 'LeaveReview',
  ReturnOrder: 'ReturnOrder',
  ReportIssue: 'ReportIssue',
  PickedOrder: 'PickedOrder',
  CheckInOrder: 'CheckInOrder',
  ManageStore: 'ManageStore',
  StoreListing: 'StoreListing',
  ManageInventory: 'ManageInventory',
  StoreDocuments: 'StoreDocuments',
  Payout: 'Payout',
  payoutStripe: 'payoutStripe',
  Subscription: 'Subscription',
  StoreEditDetail: 'StoreEditDetail',
  PaymentConfirmation: 'PaymentConfirmation',
  SpaceSubmission: 'SpaceSubmission',
  CheckAvailability: 'CheckAvailability',
  ManageFee: 'ManageFee',
  AddItem: 'AddItem',
  AddInventory: 'AddInventory',
  AddDiscount: 'AddDiscount',
  AddFee: 'AddFee',
  AddItemVendor: 'AddItemVendor',
};

export const ROLE = {
  user: 'user',
  vendor: 'vendor',
};

export const REGEX_CONST = {
  EMAIL_REGEX: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
  URL_REGEX: /^https:\/\/[a-zA-Z0-9.-]+\.(com)(\/\w+)*$/,
  ALPHABET_REGEX: /^[a-zA-Z ]*$/,
  NUMBER_REGEX: /^\d*$/,
  DECIMAL_REGEX: /^\d+(\.\d{1,5})?$/,
  ONE_DECIMAL_REGEX: /^\d*\.?\d*$/,
  TWO_DECIMAL_REGEX: /^\d*\.?\d{0,2}$/,
  THREE_DECIMAL_REGEX: /^\d*\.?\d{0,3}$/,
  FIVE_DECIMAL_REGEX: /^\d*\.?\d{0,5}$/,
  EIGHT_DECIMAL_REGEX: /^\d*\.?\d{0,8}$/,
  TEN_DECIMAL_REGEX: /^\d*\.?\d{0,10}$/,
  ALPHABET_HYPEN_REGEX: /^[a-zA-Z]*\-?[a-zA-Z]*$/,
  ALPHANUMERIC_REGEX: /^[a-zA-Z0-9]*$/,
  NUMERIC_REGEX: /^[0-9]*$/,
  NUMBER_START_DOT_OR_NOT_ZERO: /^[1-9.][0-9]*$/,
  SPACE_REGEX: /\S/,
  ALPHABET_SPACE_REGEX: /^[a-zA-Z ]*$/,
  IFSC_REGEX: /^[A-Z0-9]*$/,
  PASSWORD_REGEX:
    /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-.]).{8,}$/,
};

export const ERROR = {
  ALL: 'All field are required',
  CATEGORY: 'Please select a category',
  BPHOTOS: 'Please upload business photos ',
  SUBCATEGORY: 'Please select a sub category',
  LOCATION: 'Please enter address',
  DESCR: 'Please enter short description',
  PASSWORD:
    'Password should be six characters long, including an uppercase letter, a lowercase letter, a numeric, and a special character. ',
  PASSWORD_NOT_MATCH: 'Password and confirm password do not match.',
  NULL_PASSWORD: 'Please enter a password.',
  NULL_CONFIRM_PASSWORD: 'Please enter a confirm password.',
  NULL_PHONE: 'Please enter a phone number',
  MAIL: 'Please enter a email',
  EMAIL: 'Please enter a valid email address.',
  CHECKBOX: 'Please accept terms and conditions.',
  PHONE: 'Please enter a valid phone number.',
  CERTIFICATE: 'Please upload certificate',
  LOGO: 'Please upload logo',
  SPACE: 'Please enter valid text',
  NEW_PASSWORD: 'Please enter a new password',
  CONFIRM_PASSWORD: 'Please enter a confirm password',
  NO_OTP: 'Please enter a OTP.',
  VALID_URL: 'Please enter a valid URL',
  VALID_PASSWORD: 'Please enter a valid password',
  FNAME: 'Please enter first name',
  LNAME: 'Please enter last name',
  NAME: 'Please enter name',
};

export const SocketEvent = {
  CONNECTED_EVENT: 'connected',
  DISCONNECTED_EVENT: 'disconnect',
  MENTIONED_YOU_IN_CHAT: 'chatMention',
  NEW_MESSAGE_EVENT: 'newMessage',
  JOIN_CHAT_EVENT: 'joinChat',
  NEW_CHAT_EVENT: 'newChat',
  TYPING_EVENT: 'typing',
  STOP_TYPING_EVENT: 'stopTyping',
  LEAVE_CHAT_EVENT: 'leaveChat',
  LIKE_POST_EVENT: 'likePost',
  NEW_BOOKING: 'newBooking',
  LIKE_COMMENT_EVENT: 'likeComment',
  COMMENT_POST_EVENT: 'commentPost',
  SHARE_POST_EVENT: 'sharePost',
  GROUP_MEMBER_ADDED: 'groupMemberAdded',
  ONLINE_USERS: 'onlineUsers',
  NEW_ORDER: 'newOrder',
  ORDER_CANCELLED: 'orderCancelled',
  UNREAD_COUNT_MESSAGE: 'unreadCount',
  CHAT_LIST: 'chatList',
  NOTI_COUNT: 'notiCount',
};

