const IMAGES = {
    // mailIcon: require('../assets/images/icons/mail.png'),
    mailIcon: require('../assets/icons/mail.png'),
    openEyeIcon: require('../assets/icons/openEye.png'),
    closeEyeIcon: require('../assets/icons/closeEye.png'),
    userIcon: require('../assets/icons/user.png'),
    correctImg: require('../assets/icons/correct.png'),
    inCorrectImg: require('../assets/icons/inCorrect.png'),
    dslrImg: require('../assets/icons/dslr.png'),
    lblImg: require('../assets/icons/lbl.png'),
    videoImg: require('../assets/icons/video.png'),
    renewImg: require('../assets/icons/renew.png'),
    lensImg: require('../assets/icons/lens.png'),
    lightingImg: require('../assets/icons/lighting.png'),
    headsetImg: require('../assets/icons/headset.png'),
    gripImg: require('../assets/icons/grip.png'),

    vendorImg: require('../assets/icons/vendorImg.png'),
    vendorImg2: require('../assets/icons/vendorImg2.png'),
    vendorImg3: require('../assets/icons/vendorImg3.png'),

    stars: require('../assets/icons/stars.png'),
    ratingImg: require('../assets/icons/rating.png'),

    dummyImg: require('../assets/icons/dummy.png'),
    likeImg: require('../assets/icons/roundHeart.png'),
    heartFillImg: require('../assets/icons/heartFilled.png'),


    lightsImg: require('../assets/icons/lights.png'),
    canonImg: require('../assets/icons/canon.png'),

    thumbImg: require('../assets/icons/thumb.png'),
    likeDark: require('../assets/icons/likeDark.png'),
    like: require('../assets/icons/like.png'),
    dislike: require('../assets/icons/dislike.png'),
    dislikeDark: require('../assets/icons/dislikeDark.png'),
    checkImg: require('../assets/icons/check.png'),
    timeImg: require('../assets/icons/time.png'),
    storeImg: require('../assets/icons/store.png'),
    chatImg: require('../assets/icons/chat.png'),
    mapImg: require('../assets/icons/mapImg.png'),
    nikonImg: require('../assets/icons/nikon.png'),

    calendarImg: require('../assets/icons/calendar.png'),
    vendorProductImg: require('../assets/icons/vendorProduct.png'),
    locationImg: require('../assets/icons/location.png'),
    callImg: require('../assets/icons/call.png'),

    networkImg: require('../assets/icons/network.png'),
    fbImg: require('../assets/icons/facebook.png'),
    instaImg: require('../assets/icons/insta.png'),
    tiktokImg: require('../assets/icons/tiktok.png'),
    simpleIconImg: require('../assets/icons/Simplification.png'),
    tintCalImg: require('../assets/icons/tintCalendar.png'),

    crossImg: require('../assets/icons/cross.png'),

    VendorHomeImg: require('../assets/icons/VendorHome.png'),
    manageStore: require('../assets/icons/manageStore.png'),
    primaryCrossImg: require('../assets/icons/primaryCross.png'),
    profileImg: require('../assets/icons/profile.png'),
    adressImg: require('../assets/icons/adress.png'),
    emailImg: require('../assets/icons/email.png'),

    masterCardImg: require('../assets/icons/masterCard.png'),
    discover: require('../assets/icons/discover.png'),
    americanCardImg: require('../assets/icons/americanCard.png'),
    visaCard: require('../assets/icons/visaCard.png'),
    truckImg: require('../assets/icons/truck.png'),

    insuranceImg: require('../assets/icons/insurance.png'),
    metricImg: require('../assets/icons/metrics.png'),
    helpImg: require('../assets/icons/help.png'),
    favImg: require('../assets/icons/fav.png'),
    verifyImg: require('../assets/icons/verify.png'),
    notifiImg: require('../assets/icons/notification.png'),
    moneyImg: require('../assets/icons/money.png'),

    activeOderImg: require('../assets/icons/activeOder.png'),
    completedOderImg: require('../assets/icons/completedOder.png'),
    customersImg: require('../assets/icons/customers.png'),

    creditCardImg: require('../assets/icons/creditCard.png'),
    reciptImg: require('../assets/icons/receipt.png'),
    uploadImg: require('../assets/icons/upload.png'),
    tracedImg: require('../assets/icons/traced.png'),
    circle: require('../assets/icons/circle.png'),
    selectedCircle: require('../assets/icons/selectedCircle.png'),

    banner: require('../assets/icons/banner.png'),

    idIcon: require('../assets/icons/idCard.png'),
    scanIcon: require('../assets/icons/profileScan.png'),
    PhoneVerify: require('../assets/icons/phoneVerify.png'),
    mailVerify: require('../assets/icons/mailVerify.png'),
    officialTag: require('../assets/icons/official.png'),
    unofficialTag: require('../assets/icons/primaryCross.png'),

    transaction: require('../assets/icons/transaction.png'),
    lightReview: require('../assets/icons/lightReview.png'),
    click: require('../assets/icons/click.png'),
    camIcon: require('../assets/icons/cam.png'),

    inventory: require('../assets/icons/inventory.png'),
    payout: require('../assets/icons/payout.png'),
    storeListing: require('../assets/icons/storeListing.png'),
    storeDoc: require('../assets/icons/storeDoc.png'),
    subscription: require('../assets/icons/subscription.png'),
    filter: require('../assets/icons/filter.png'),
    updatedFilter: require('../assets/icons/updatedFilter.png'),
    newFilter: require('../assets/icons/newFilter.png'),
    bar: require('../assets/icons/bar.png'),
    mediaDummy: require('../assets/icons/media.png'),

    square: require('../assets/icons/square.png'),
    checkedSquare: require('../assets/icons/checkedSquare.png'),
    profilePlaceholder: require('../assets/icons/pro.png'),
    placeholder: require('../assets/icons/person.png'),

    roundPin: require('../assets/icons/roundPin.png'),
    noCart: require('../assets/icons/noCart.png'),
    noRent: require('../assets/icons/noRent.png'),
    bannerAdd: require('../assets/icons/bannerAdd.png'),
    cloud: require('../assets/icons/cloud.png'),
    dots: require('../assets/icons/dots.png'),
    add: require('../assets/icons/add.png'),
    visa: require('../assets/icons/Visa.png'),
    achvisa: require('../assets/icons/Achvisa.png'),
    logo: require('../assets/icons/Logo.jpeg'),
    verified: require('../assets/icons/verified.png'),
    card: require('../assets/icons/card.png'),
    expiry: require('../assets/icons/expiry.png'),
    lock: require('../assets/icons/lock.png'),
    info: require('../assets/icons/info.png'),
    vendorIcon: require('../assets/icons/vendorIcon.png'),
}
export default IMAGES;