export const VideoCallUpperImg = require('../../assets/images/png/videoCallUpper.png');
export const VideoCallLowerImg = require('../../assets/images/png/videoCallLower.png');
export const ChatBackgroundImg = require('../../assets/images/png/chatBackground.png');
export const Chatimg1Img = require('../../assets/images/png/chatImg1.png');
export const Chatimg2Img = require('../../assets/images/png/chatImg2.png');
export const Chatimg3Img = require('../../assets/images/png/chatImg3.png');
export const Chatimg4Img = require('../../assets/images/png/chatImg4.png');
export const Chatimg5Img = require('../../assets/images/png/chatImg5.png');
export const Chatimg6Img = require('../../assets/images/png/chatImg6.png');
export const Chatimg7Img = require('../../assets/images/png/chatImg7.png');
export const Chatimg8Img = require('../../assets/images/png/chatImg8.png');
export const Chatimg9Img = require('../../assets/images/png/chatImg9.png');
export const GroupImg1Img = require('../../assets/images/png/groupImg1.png');
export const GroupImg2Img = require('../../assets/images/png/groupImg2.png');
export const GroupImg3Img = require('../../assets/images/png/groupImg3.png');
export const GroupImg4Img = require('../../assets/images/png/groupImg4.png');
export const GroupImg5Img = require('../../assets/images/png/groupImg5.png');
export const GroupImg6Img = require('../../assets/images/png/groupImg6.png');
export const GroupImg7Img = require('../../assets/images/png/groupImg7.png');
export const ProfileImg = require('../../assets/images/png/profile.png');
export const PurpleSignalImg = require('../../assets/images/png/purpleSignal.png');
export const GreenSignalImg = require('../../assets/images/png/greenSignal.png');
export const YellowSignalImg = require('../../assets/images/png/yellowSignal.png');
export const BlueSignalImg = require('../../assets/images/png/blueSignal.png');
export const GroupVideoCallImg1 = require('../../assets/images/png/videoCallImg1.png');
export const GroupVideoCallImg2 = require('../../assets/images/png/videoCallImg2.png');
export const GroupVideoCallImg3 = require('../../assets/images/png/videoCallImg3.png');
export const MediaImg1 = require('../../assets/images/png/galleryImg1.png');
export const MediaImg2 = require('../../assets/images/png/galleryImg2.png');
export const MediaImg3 = require('../../assets/images/png/galleryImg3.png');
export const MediaImg4 = require('../../assets/images/png/galleryImg4.png');
export const QrCodeImg = require('../../assets/images/png/qrCode.png');
export const UserImg = require('../../assets/images/png/userImg.png');
export const UsFlagTmg = require('../../assets/images/png/usFlag.png');
export const GrpImg_1 = require('../../assets/images/png/grpImg1.png');
export const GrpImg_2 = require('../../assets/images/png/grpImg2.png');
export const DocImg1= require('../../assets/images/png/docsImg1.png');
export const DocImg2= require('../../assets/images/png/docsImg2.png');
export const DocImg3= require('../../assets/images/png/docsImg3.png');
export const DocImg4= require('../../assets/images/png/docsImg4.png');
export const DocImg5= require('../../assets/images/png/docsImg5.png');
export const DocImg6= require('../../assets/images/png/docsImg6.png');
export const DocImg7= require('../../assets/images/png/docsImg7.png');
export const DocImg8= require('../../assets/images/png/docsImg8.png');
export const StatusPic1 = require('../../assets/images/png/statusPic1.png');
export const StatusPic2 = require('../../assets/images/png/statusPic2.png');
export const StatusPic3 = require('../../assets/images/png/statusPic3.png');
export const StatusPic4 = require('../../assets/images/png/statusPic4.png');
export const StatusPic5 = require('../../assets/images/png/statusPic5.png');
export const ViewPic1 = require('../../assets/images/png/viewPic1.png')
export const ViewPic2 = require('../../assets/images/png/viewPic2.png')
export const ViewPic3 = require('../../assets/images/png/viewPic3.png')
export const MutePic1 = require('../../assets/images/png/mutePic1.png')
export const MutePic2 = require('../../assets/images/png/mutePic2.png')
export const ImageImg1= require('../../assets/images/png/recentImg1.png');
export const ImageImg2= require('../../assets/images/png/recentImg2.png');
export const ImageImg3= require('../../assets/images/png/recentImg3.png');
export const ImageImg4= require('../../assets/images/png/recentImg4.png');
export const ImageImg5= require('../../assets/images/png/recentImg5.png');
export const ImageImg6= require('../../assets/images/png/recentImg6.png');
export const ImageImg7= require('../../assets/images/png/recentImg7.png');
export const Videoimg1=require('../../assets/images/png/videoImg1.png')
export const Videoimg2=require('../../assets/images/png/videoImg2.png')
export const Videoimg3=require('../../assets/images/png/videoImg3.png')
export const Videoimg4=require('../../assets/images/png/videoImg4.png')
export const Videoimg5=require('../../assets/images/png/videoImg5.png')
export const Videoimg6=require('../../assets/images/png/videoImg6.png')
export const Videoimg7=require('../../assets/images/png/videoImg7.png')
export const Videoimg8=require('../../assets/images/png/videoImg8.png')
export const Videoimg9=require('../../assets/images/png/videoImg9.png')
export const Videoimg10=require('../../assets/images/png/videoImg10.png')
export const Linkimg1=require('../../assets/images/png/linkImg1.png')
export const Linkimg2=require('../../assets/images/png/linkImg2.png')
export const Linkimg3=require('../../assets/images/png/linkImg3.png')
export const Linkimg4=require('../../assets/images/png/linkImg4.png')
export const Wallpaper1=require('../../assets/images/png/wallpaper1.png')
export const Wallpaper2=require('../../assets/images/png/wallpaper2.png')
export const Wallpaper3=require('../../assets/images/png/wallpaper3.png')
export const Wallpaper4=require('../../assets/images/png/wallpaper4.png')
export const Wallpaper5=require('../../assets/images/png/wallpaper5.png')
export const Wallpaper6=require('../../assets/images/png/wallpaper6.png')
export const Wallpaper7=require('../../assets/images/png/wallpaper7.png')
export const Wallpaper8=require('../../assets/images/png/wallpaper8.png')
export const Wallpaper9=require('../../assets/images/png/wallpaper9.png')
export const Wallpaper10=require('../../assets/images/png/wallpaper10.png')
export const Wallpaper11=require('../../assets/images/png/wallpaper11.png')
export const Wallpaper12=require('../../assets/images/png/wallpaper12.png')
export const StatusImg1 = require('../../assets/images/png/statusImg1.png');
export const AuthImageBg =require('../../assets/images/png/backgroundImage.png');
export const AuthImageBottom =require('../../assets/images/png/welcomepageBottom.png');
