export const REGEX_CONST = {
  EMAIL_REGEX: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
  URL_REGEX: /^https:\/\/[a-zA-Z0-9.-]+\.(com)(\/\w+)*$/,
  ALPHABET_REGEX: /^[a-zA-Z ]*$/,
  NUMBER_REGEX: /^\d*$/,
  DECIMAL_REGEX: /^\d+(\.\d{1,5})?$/,
  ONE_DECIMAL_REGEX: /^\d*\.?\d*$/,
  TWO_DECIMAL_REGEX: /^\d*\.?\d{0,2}$/,
  THREE_DECIMAL_REGEX: /^\d*\.?\d{0,3}$/,
  FIVE_DECIMAL_REGEX: /^\d*\.?\d{0,5}$/,
  EIGHT_DECIMAL_REGEX: /^\d*\.?\d{0,8}$/,
  TEN_DECIMAL_REGEX: /^\d*\.?\d{0,10}$/,
  ALPHABET_HYPEN_REGEX: /^[a-zA-Z]*\-?[a-zA-Z]*$/,
  ALPHANUMERIC_REGEX: /^[a-zA-Z0-9]*$/,
  NUMERIC_REGEX: /^[0-9]*$/,
  NUMBER_START_DOT_OR_NOT_ZERO: /^[1-9.][0-9]*$/,
  SPACE_REGEX: /\S/,
  ALPHABET_SPACE_REGEX: /^[a-zA-Z ]*$/,
  IFSC_REGEX: /^[A-Z0-9]*$/,
  PASSWORD_REGEX:
    /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-.]).{8,}$/,
};

export const ERROR = {
  ALL: 'All field are required.',
  CATEGORY: 'Please select a category.',
  BPHOTOS: 'Please upload business photos.',
  SUBCATEGORY: 'Please select a sub category.',
  LOCATION: 'Please enter address.',
  DESCR: 'Please enter short description.',
  PASSWORD:
    'Password should be six characters long, including an uppercase letter, a lowercase letter, a numeric, and a special character.',
  PASSWORD_LENGTH: 'Password should be at least 6 characters long.',
  PASSWORD_MISMATCH: 'Password and confirm password do not match.',
  NULL_PASSWORD: 'Please enter a password.',
  NULL_FIRST_NAME: 'Please enter a first name.',
  NULL_LAST_NAME: 'Please enter a last name.',
  NULL_PATIENT_CODE: 'Please enter a patient code.',
  NULL_CONFIRM_PASSWORD: 'Please enter a confirm password.',
  NULL_PHONE: 'Please enter a phone number.',
  MAIL: 'Please enter a email.',
  EMAIL: 'Please enter a valid email address.',
  CHECKBOX: 'Please accept terms and conditions.',
  PHONE: 'Please enter a valid phone number.',
  CERTIFICATE: 'Please upload certificate.',
  LOGO: 'Please upload logo.',
  SPACE: 'Please enter valid text.',
  NEW_PASSWORD: 'Please enter a new password.',
  CONFIRM_PASSWORD: 'Please enter a confirm password.',
  NO_OTP: 'Please enter a OTP.',
  VALID_URL: 'Please enter a valid URL.',
  VALID_PASSWORD: 'Please enter a valid password.',
  FNAME: 'Please enter first name.',
  LNAME: 'Please enter last name.',
  NAME: 'Please enter name.',
};
